name: SAFK
main: org.game_host.cegryphony.SAFK
version: 0.1
commands:
    afk:
        description: Teleports you to the AFK shelter.
        usage: /<command>
        permissions: SAFK.afk
    setafk:
        description: Sets the AFK shelter.
        usage: /<command>
        permissions: SAFK.setafk
        